"""Seed the database with sample books, categories, and a demo user."""
# flake8: noqa: E501
from database import engine, SessionLocal, Base
import models
from passlib.context import CryptContext

pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")


CATEGORIES = [
    {"name": "Fiction", "slug": "fiction", "description": "Novels, short stories, and literary fiction"},
    {"name": "Non-Fiction", "slug": "non-fiction", "description": "Biographies, history, science, and more"},
    {"name": "Science Fiction", "slug": "sci-fi", "description": "Futuristic and speculative fiction"},
    {"name": "Mystery & Thriller", "slug": "mystery-thriller", "description": "Crime, suspense, and detective stories"},
    {"name": "Self-Help", "slug": "self-help", "description": "Personal development and productivity"},
    {"name": "Fantasy", "slug": "fantasy", "description": "Magical worlds and epic adventures"},
    {"name": "Biography", "slug": "biography", "description": "Life stories of remarkable people"},
    {"name": "Children's", "slug": "childrens", "description": "Books for young readers"},
]

BOOKS = [
    # Fiction
    {
        "title": "The Midnight Library",
        "author": "Matt Haig",
        "isbn": "978-0525559474",
        "price": 14.99,
        "original_price": 18.99,
        "description": "Between life and death there is a library, and within that library, the shelves go on forever. Every book provides a chance to try another life you could have lived. To see how things would be if you had made other choices.",
        "cover_image": "https://covers.openlibrary.org/b/id/10521270-L.jpg",
        "pages": 288,
        "publisher": "Viking",
        "published_date": "2020",
        "rating": 4.3,
        "review_count": 12450,
        "featured": True,
        "bestseller": True,
        "category": "fiction",
        "stock": 42,
    },
    {
        "title": "Lessons in Chemistry",
        "author": "Bonnie Garmus",
        "isbn": "978-0385547345",
        "price": 16.99,
        "original_price": 22.00,
        "description": "Chemist Elizabeth Zott is not your average woman. In fact, Elizabeth Zott would be the first to point out that there is no such thing as an average woman.",
        "cover_image": "https://covers.openlibrary.org/b/id/12893049-L.jpg",
        "pages": 390,
        "publisher": "Doubleday",
        "published_date": "2022",
        "rating": 4.5,
        "review_count": 18230,
        "featured": True,
        "bestseller": True,
        "category": "fiction",
        "stock": 35,
    },
    {
        "title": "Tomorrow, and Tomorrow, and Tomorrow",
        "author": "Gabrielle Zevin",
        "isbn": "978-0593321201",
        "price": 15.99,
        "original_price": 28.00,
        "description": "A dazzling novel about love, creativity, and the redemptive power of games.",
        "cover_image": "https://covers.openlibrary.org/b/id/12887009-L.jpg",
        "pages": 480,
        "publisher": "Knopf",
        "published_date": "2022",
        "rating": 4.4,
        "review_count": 9870,
        "featured": False,
        "bestseller": True,
        "new_arrival": False,
        "category": "fiction",
        "stock": 28,
    },
    {
        "title": "The Covenant of Water",
        "author": "Abraham Verghese",
        "isbn": "978-0802162175",
        "price": 19.99,
        "original_price": 32.00,
        "description": "A sweeping multigenerational saga set in South India, spanning seventy years and three generations of a family.",
        "cover_image": "https://covers.openlibrary.org/b/id/13262619-L.jpg",
        "pages": 736,
        "publisher": "Grove Press",
        "published_date": "2023",
        "rating": 4.6,
        "review_count": 6540,
        "new_arrival": True,
        "category": "fiction",
        "stock": 20,
    },
    # Science Fiction
    {
        "title": "Project Hail Mary",
        "author": "Andy Weir",
        "isbn": "978-0593135204",
        "price": 14.99,
        "original_price": 28.00,
        "description": "A lone astronaut must save the earth from disaster in this propulsive, gripping thriller that is perfect for fans of The Martian.",
        "cover_image": "https://covers.openlibrary.org/b/id/10521580-L.jpg",
        "pages": 476,
        "publisher": "Ballantine Books",
        "published_date": "2021",
        "rating": 4.8,
        "review_count": 25600,
        "featured": True,
        "bestseller": True,
        "category": "sci-fi",
        "stock": 55,
    },
    {
        "title": "The Three-Body Problem",
        "author": "Liu Cixin",
        "isbn": "978-0765382030",
        "price": 13.99,
        "original_price": 17.00,
        "description": "Set against the backdrop of China's Cultural Revolution, a secret military project sends signals into space to establish contact with aliens.",
        "cover_image": "https://covers.openlibrary.org/b/id/8739161-L.jpg",
        "pages": 400,
        "publisher": "Tor Books",
        "published_date": "2014",
        "rating": 4.3,
        "review_count": 31200,
        "bestseller": True,
        "category": "sci-fi",
        "stock": 47,
    },
    {
        "title": "Exhalation: Stories",
        "author": "Ted Chiang",
        "isbn": "978-1101947913",
        "price": 12.99,
        "original_price": 17.00,
        "description": "Nine wondrous tales that grapple with the nature of time, consciousness, and the staggering size of the universe.",
        "cover_image": "https://covers.openlibrary.org/b/id/10521271-L.jpg",
        "pages": 352,
        "publisher": "Knopf",
        "published_date": "2019",
        "rating": 4.6,
        "review_count": 14300,
        "category": "sci-fi",
        "stock": 30,
    },
    # Mystery & Thriller
    {
        "title": "The Thursday Murder Club",
        "author": "Richard Osman",
        "isbn": "978-1984880963",
        "price": 13.99,
        "original_price": 27.00,
        "description": "In a peaceful retirement village, four unlikely friends meet weekly to investigate unsolved murders. But when a real murder occurs, things get personal.",
        "cover_image": "https://covers.openlibrary.org/b/id/10521272-L.jpg",
        "pages": 382,
        "publisher": "Viking",
        "published_date": "2020",
        "rating": 4.2,
        "review_count": 22100,
        "featured": True,
        "bestseller": True,
        "category": "mystery-thriller",
        "stock": 38,
    },
    {
        "title": "Remarkably Bright Creatures",
        "author": "Shelby Van Pelt",
        "isbn": "978-0063204157",
        "price": 15.99,
        "original_price": 27.00,
        "description": "A widowed woman befriends a giant Pacific octopus who helps her uncover a mystery from the past.",
        "cover_image": "https://covers.openlibrary.org/b/id/12611989-L.jpg",
        "pages": 360,
        "publisher": "Ecco",
        "published_date": "2022",
        "rating": 4.4,
        "review_count": 16800,
        "new_arrival": False,
        "bestseller": True,
        "category": "mystery-thriller",
        "stock": 25,
    },
    {
        "title": "The Maid",
        "author": "Nita Prose",
        "isbn": "978-0593314425",
        "price": 12.99,
        "original_price": 27.00,
        "description": "Molly the Maid discovers a dead body in the Regency Grand Hotel and must clear her name in this charming mystery.",
        "cover_image": "https://covers.openlibrary.org/b/id/12309729-L.jpg",
        "pages": 304,
        "publisher": "Ballantine Books",
        "published_date": "2022",
        "rating": 4.1,
        "review_count": 13900,
        "category": "mystery-thriller",
        "stock": 22,
    },
    # Self-Help
    {
        "title": "Atomic Habits",
        "author": "James Clear",
        "isbn": "978-0735211292",
        "price": 16.99,
        "original_price": 27.00,
        "description": "No matter your goals, Atomic Habits offers a proven framework for improving—every day. The most practical guide to breaking bad habits and building good ones.",
        "cover_image": "https://covers.openlibrary.org/b/id/10521273-L.jpg",
        "pages": 320,
        "publisher": "Avery",
        "published_date": "2018",
        "rating": 4.8,
        "review_count": 89400,
        "featured": True,
        "bestseller": True,
        "category": "self-help",
        "stock": 100,
    },
    {
        "title": "The Power of Now",
        "author": "Eckhart Tolle",
        "isbn": "978-1577314806",
        "price": 13.99,
        "original_price": 17.00,
        "description": "A guide to spiritual enlightenment that has transformed millions of lives. Tolle shows that suffering is unnecessary.",
        "cover_image": "https://covers.openlibrary.org/b/id/8739162-L.jpg",
        "pages": 229,
        "publisher": "New World Library",
        "published_date": "1997",
        "rating": 4.5,
        "review_count": 52000,
        "bestseller": True,
        "category": "self-help",
        "stock": 75,
    },
    {
        "title": "Think Again",
        "author": "Adam Grant",
        "isbn": "978-1984878106",
        "price": 15.99,
        "original_price": 28.00,
        "description": "The ability to rethink and unlearn, in ourselves and in the communities we live in, is the most important skill of the 21st century.",
        "cover_image": "https://covers.openlibrary.org/b/id/10521274-L.jpg",
        "pages": 307,
        "publisher": "Viking",
        "published_date": "2021",
        "rating": 4.4,
        "review_count": 18700,
        "new_arrival": False,
        "category": "self-help",
        "stock": 60,
    },
    # Fantasy
    {
        "title": "The Name of the Wind",
        "author": "Patrick Rothfuss",
        "isbn": "978-0756404079",
        "price": 14.99,
        "original_price": 19.00,
        "description": "The tale of the legendary figure Kvothe — from his childhood in a troupe of traveling players, to his years spent as a near-feral orphan in a crime-ridden city.",
        "cover_image": "https://covers.openlibrary.org/b/id/8739163-L.jpg",
        "pages": 662,
        "publisher": "DAW Books",
        "published_date": "2007",
        "rating": 4.6,
        "review_count": 42000,
        "featured": True,
        "bestseller": True,
        "category": "fantasy",
        "stock": 45,
    },
    {
        "title": "Fourth Wing",
        "author": "Rebecca Yarros",
        "isbn": "978-1649374042",
        "price": 18.99,
        "original_price": 29.00,
        "description": "Twenty-year-old Violet Sorrengail was supposed to enter the Scribe Quadrant, but instead she's forced into the riders' quadrant — surrounded by dragons.",
        "cover_image": "https://covers.openlibrary.org/b/id/13262620-L.jpg",
        "pages": 528,
        "publisher": "Entangled: Red Tower Books",
        "published_date": "2023",
        "rating": 4.7,
        "review_count": 34500,
        "featured": True,
        "bestseller": True,
        "new_arrival": True,
        "category": "fantasy",
        "stock": 65,
    },
    # Biography
    {
        "title": "Spare",
        "author": "Prince Harry",
        "isbn": "978-0593593806",
        "price": 17.99,
        "original_price": 36.00,
        "description": "The candid, unflinching memoir by the Duke of Sussex about his life inside and outside of the Royal Family.",
        "cover_image": "https://covers.openlibrary.org/b/id/13050259-L.jpg",
        "pages": 416,
        "publisher": "Random House",
        "published_date": "2023",
        "rating": 3.9,
        "review_count": 27800,
        "bestseller": True,
        "category": "biography",
        "stock": 33,
    },
    {
        "title": "Greenlights",
        "author": "Matthew McConaughey",
        "isbn": "978-0593139134",
        "price": 15.99,
        "original_price": 32.00,
        "description": "A memoir of raucous stories, outlaw wisdom, and lessons learned the hard way from the Academy Award-winning actor.",
        "cover_image": "https://covers.openlibrary.org/b/id/10521275-L.jpg",
        "pages": 304,
        "publisher": "Crown",
        "published_date": "2020",
        "rating": 4.5,
        "review_count": 21000,
        "category": "biography",
        "stock": 28,
    },
    # Non-Fiction
    {
        "title": "Sapiens: A Brief History of Humankind",
        "author": "Yuval Noah Harari",
        "isbn": "978-0062316097",
        "price": 16.99,
        "original_price": 22.00,
        "description": "How did Homo sapiens evolve from a minor primate to the ruler of the world? Harari takes us on a breathtaking journey through the history of our species.",
        "cover_image": "https://covers.openlibrary.org/b/id/8739164-L.jpg",
        "pages": 443,
        "publisher": "Harper",
        "published_date": "2015",
        "rating": 4.6,
        "review_count": 68200,
        "featured": True,
        "bestseller": True,
        "category": "non-fiction",
        "stock": 80,
    },
    {
        "title": "The Body: A Guide for Occupants",
        "author": "Bill Bryson",
        "isbn": "978-0385539302",
        "price": 17.99,
        "original_price": 30.00,
        "description": "A grand tour of the human body. From head to toe, Bryson explores the body's hidden complexities and extraordinary resilience.",
        "cover_image": "https://covers.openlibrary.org/b/id/10521276-L.jpg",
        "pages": 449,
        "publisher": "Doubleday",
        "published_date": "2019",
        "rating": 4.5,
        "review_count": 19300,
        "category": "non-fiction",
        "stock": 40,
    },
    # Children's
    {
        "title": "The Very Hungry Caterpillar",
        "author": "Eric Carle",
        "isbn": "978-0399226908",
        "price": 8.99,
        "original_price": 10.99,
        "description": "The classic picture book about a very hungry caterpillar's journey through the week. Perfect for the very youngest readers.",
        "cover_image": "https://covers.openlibrary.org/b/id/8739165-L.jpg",
        "pages": 26,
        "publisher": "Philomel Books",
        "published_date": "1969",
        "rating": 4.9,
        "review_count": 95000,
        "featured": True,
        "bestseller": True,
        "category": "childrens",
        "stock": 120,
    },
    {
        "title": "Harry Potter and the Sorcerer's Stone",
        "author": "J.K. Rowling",
        "isbn": "978-0590353427",
        "price": 12.99,
        "original_price": 14.99,
        "description": "Harry Potter has never been the star of a Quidditch team, scoring points while riding a broom far above the ground. He knows no spells, has never helped to hatch a dragon.",
        "cover_image": "https://covers.openlibrary.org/b/id/10521277-L.jpg",
        "pages": 309,
        "publisher": "Scholastic",
        "published_date": "1998",
        "rating": 4.9,
        "review_count": 150000,
        "featured": True,
        "bestseller": True,
        "category": "childrens",
        "stock": 200,
    },
]


def seed():
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()

    if db.query(models.Category).count() > 0:
        print("Database already seeded.")
        db.close()
        return

    cat_map = {}
    for cat_data in CATEGORIES:
        cat = models.Category(**cat_data)
        db.add(cat)
        db.flush()
        cat_map[cat.slug] = cat.id

    for book_data in BOOKS:
        data = dict(book_data)
        cat_slug = data.pop("category")
        data["category_id"] = cat_map.get(cat_slug)
        book = models.Book(**data)
        db.add(book)

    demo_user = models.User(
        name="Demo User",
        email="demo@bookstore.com",
        hashed_password=pwd_context.hash("demo1234"),
        address="123 Main Street, Booktown, BK 10001",
        phone="+1 (555) 000-0000",
    )
    db.add(demo_user)
    db.commit()
    print(f"Seeded {len(CATEGORIES)} categories and {len(BOOKS)} books.")
    db.close()


if __name__ == "__main__":
    seed()
